name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Prepare the environment.
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.x"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: "2.8.0"
      - name: Install tools
        run: |
          KEEPARELEASE_VERSION=1.2.0
          mkdir -p bin
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.21.0
          curl -sLO https://github.com/rgreinho/keeparelease/releases/download/${KEEPARELEASE_VERSION}/keeparelease-${KEEPARELEASE_VERSION}-linux-amd64
          chmod a+x keeparelease-${KEEPARELEASE_VERSION}-linux-amd64
          mv keeparelease-${KEEPARELEASE_VERSION}-linux-amd64 bin/keeparelease
          echo "::add-path::$GITHUB_WORKSPACE/bin"

      # Setup the project.
      - name: setup the project
        run: go mod download

      # Run the checks.
      - name: Run the linters.
        run: task lint
      - name: Run the unit tests.
        run: task test
      - name: Build the binaries.
        run: task build

      # Publish a new release when a tag is created.
      - name: Prepare release content
        run: keeparelease -x > ${{ github.workflow }}-release.md
      - name: Publish the release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workflow }}-release.md
          files: |
            dist/*
      - name: Publish the release
        if: startsWith(github.event.ref, 'refs/tags')
        run: task release
