name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Prepare the environment.
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.x"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: "2.8.0"
      - name: Install tools
        run: |
          curl -sLO https://github.com/rgreinho/keeparelease/releases/download/1.1.2/keeparelease-1.1.2-linux-amd64
          chmod a+x keeparelease-1.1.2-linux-amd64
          mkdir -p bin
          mv keeparelease-1.1.2-linux-amd64 bin/keeparelease
          echo "::add-path::$GITHUB_WORKSPACE/bin"

      - name: Setup the project
        run: go mod download

      - name: Build the binaries.
        run: task build

      - name: Publish the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: task release
